### ISSUE TITLE
模型属性支持外键，界面支持选择

### ISSUE THREAD

**Issue by wingyiu** [veops/cmdb#128]
1:N，N侧模型支持添加外键attr，并且可以从1侧直接选择。自动添加一个belong_to的关联关系。

比如Pod模型，有一属性表示属于某个PSA（Product/Service/App)，录入时可以直接选择并且校验

**Comment by pycook** [comment]
现在的模型之间的关系不是用属性作为外键来进行关联的

**Comment by wingyiu** [comment]
> 

但使用上，录入数据时，还是级联下拉菜单更方便高效

**Comment by pycook** [comment]
> > 
> 
> 但使用上，录入数据时，还是级联下拉菜单更方便高效

2.3.2版本已经支持
