### ISSUE TITLE
老师，为什么我部署登录cmdb系统后ACL的用户密钥位置没有key和secret啊，空值而且不可编辑

### ISSUE THREAD

**Issue by wuxiao-ling197** [veops/cmdb#185]

**Comment by pycook** [comment]
因为初始SQL admin用户的key和secret为空，我们将会修改，空值也允许重置密钥

**Comment by wuxiao-ling197** [comment]
但是我发现重置之后还是为空诶，这个怎么处理？谢谢老师回复发自我的手机-------- 原始邮件 --------发件人： pycook ***@***.***>日期： 2023年9月27日周三 20:12收件人： veops/cmdb ***@***.***>抄送： wuxiao-ling197 ***@***.***>, Author ***@***.***>主    题： Re: [veops/cmdb] 老师，为什么我部署登录cmdb系统后ACL的用户密钥位置没有key和secret啊，空值而且不可编辑 (Issue #185)
因为初始SQL admin用户的key和secret为空，我们将会修改，空值也允许重置密钥

**Comment by pycook** [comment]
因为目前前端限制了不能为空，所以空值没法发起请求到后端

**Comment by wuxiao-ling197** [comment]
所以这个问题要怎么解决啊发自我的手机-------- 原始邮件 --------发件人： pycook ***@***.***>日期： 2023年9月28日周四 09:42收件人： veops/cmdb ***@***.***>抄送： wuxiao-ling197 ***@***.***>, Author ***@***.***>主    题： Re: [veops/cmdb] 老师，为什么我部署登录cmdb系统后ACL的用户密钥位置没有key和secret啊，空值而且不可编辑 (Issue #185)
因为目前前端限制了不能为空，所以空值没法发起请求到后端

**Comment by pycook** [comment]
下个版本修复这个问题
