### ISSUE TITLE
docker模式下启用公司信息编辑

### ISSUE THREAD

**Issue by coalzhao** [veops/cmdb#198]
docker启动下如何启用编辑公司信息，在cmdb-api这个container里面执行了flask init-department也不起作用

**Comment by pycook** [comment]
#200 fix了init-department @coalzhao

**Comment by coalzhao** [comment]
> #200 fix了init-department @coalzhao

clone了github最新的代码,使用docker拉取run起来以后还是一样的,试过退出再登录,或是重启container,都是一样的不可修改
![image](https://github.com/veops/cmdb/assets/22334888/a42d53c7-78b7-4c75-b1e1-2b5bdf3aa016)
![image](https://github.com/veops/cmdb/assets/22334888/495c2991-6540-4f5e-8d33-710a9a8f9523)
![image](https://github.com/veops/cmdb/assets/22334888/5d5b0168-0fcc-4082-87e6-678e2efff78d)

**Comment by coalzhao** [comment]
> #200 fix了init-department @coalzhao

OK了,可以了
