### ISSUE TITLE
业务关系模型定义后侧边导航栏展示问题

### ISSUE THREAD

**Issue by lxyqwer** [veops/cmdb#204]
![image](https://github.com/veops/cmdb/assets/30629682/a70c2bed-6498-4739-8320-173baa0edef1)
定义了两个业务关系模型侧边展示如下
![image](https://github.com/veops/cmdb/assets/30629682/c94fafb3-f319-45cb-851c-27ef91335fd5)
![image](https://github.com/veops/cmdb/assets/30629682/77ecaad8-8fae-48e8-b3d9-2ae5ad797f71)

**Comment by pycook** [comment]
@lxyqwer 你是说有显示空白吗 能描述详细点么

**Comment by lxyqwer** [comment]
> @lxyqwer 你是说有显示空白吗 能描述详细点么

是的，我定义的产品和运维组件都在事业部下面，看 api 会返回产品+运维组件所有数据

**Comment by lxyqwer** [comment]
> @lxyqwer 你是说有显示空白吗 能描述详细点么

空白<li>+能显示的正好是 api 返回的全部数据的个数

**Comment by wang-liang0615** [comment]
已fix    https://github.com/veops/cmdb/pull/208

**Comment by pycook** [comment]
@lxyqwer 你可以用master分支代码验证下

**Comment by lxyqwer** [comment]
> @lxyqwer 你可以用master分支代码验证下

可以了
