### ISSUE TITLE
树分叉显示重复

### ISSUE THREAD

**Issue by ssrshz** [veops/cmdb#212]
模型关系定义如下：
<img width="285" alt="image" src="https://github.com/veops/cmdb/assets/19809226/3d899ce6-e4f5-42a7-94c2-53e7688cfd09">
树定义：
<img width="619" alt="image" src="https://github.com/veops/cmdb/assets/19809226/a5054163-3b6e-4aa9-88b0-d2b7cf83f370">

在stage--》Azure_HK添加cluster时树重复显示bug：
<img width="222" alt="image" src="https://github.com/veops/cmdb/assets/19809226/91362886-6eb3-441b-ba13-91d02e252cb3">

**Comment by pycook** [comment]
要确认下Azure_HK是不是和Prod和Stage之间都建立了关系 @ssrshz

**Comment by ssrshz** [comment]
> 要确认下Azure_HK是不是和Prod和Stage之间都建立了关系 @ssrshz

问题就在这里，Prod和Stage属于环境，每个环境有不同的集群，实际情况则是，cluster_1在Stage存在，在Prod不存在。

<img width="662" alt="image" src="https://github.com/veops/cmdb/assets/19809226/8b6318ce-c5de-495b-8f4f-5ee5225968fa">

应该如何解决？

**Comment by pycook** [comment]
目前只支持一对多的关系来构建这个tree，你这是多对多，环境和区域一般我们可能就直接放属性了。
后面考虑下如何支持这种多对多关系的服务树

**Comment by ssrshz** [comment]
> 目前只支持一对多的关系来构建这个tree，你这是多对多，环境和区域一般我们可能就直接放属性了。 后面考虑下如何支持这种多对多关系的服务树

期待支持

**Comment by ssrshz** [comment]
@pycook 那目前关系配置中，有多对多选项，那这个用于什么场景？

**Comment by pycook** [comment]
> @pycook 那目前关系配置中，有多对多选项，那这个用于什么场景？

这个只是加关系的一种限制而已。因为服务树或者关系视图是自定义的，也是通用的，所以多对多支持有一定的复杂度，这个看能否在下个版本支持下。

**Comment by ssrshz** [comment]
> > @pycook 那目前关系配置中，有多对多选项，那这个用于什么场景？
> 
> 这个只是加关系的一种限制而已。因为服务树或者关系视图是自定义的，也是通用的，所以多对多支持有一定的复杂度，这个看能否在下个版本支持下。

Get it. 通常来说，如果某一个操作会影响功能(这里即指多对多重复呈现），就应该加以限制，要不然就会很困惑，出现未按照预期的场景，尤其建模的时候。
不过多对多用在叶子节点，就非常适合，只要不出现在中间节点。

总体测试下来，veops/cmdb是不错的产品，足够灵活与包容，以不变应万变。假以时日，会大火的，come on

**Comment by pycook** [comment]
@ssrshz 你提的这个关系视图的多对多将会在下个版本支持，至少能cover你这个场景。

实际上，你这个场景如果不用关系视图，用**资源层级**视图的方式就可以满足，只不过环境、区域、集群、NameSpace这4个是作为属性存在于Node这个模型里。这样就可以自定义出你需要的tree。
资源层级视图定义文档见: https://veops.cn/docs/cmdb/tree/

**Comment by pycook** [comment]
@ssrshz 你能描述下整个链路么  环境-> 区域 -> 集群 -> namespace -> node 之间的关系   是多对多还是1对多

**Comment by ssrshz** [comment]
> @ssrshz 你能描述下整个链路么 环境-> 区域 -> 集群 -> namespace -> node 之间的关系 是多对多还是1对多

是这样的，我们目前的环境可以分布在多个区域，比如测试环境，在上海办公室，北京办公室都存在，命名都是test

所以环境与区域是多对多。

区域里又可以包括个集群，而集群只能位于一个区域，区域与集群之间是一对多

集群可以包括多个namespace，namespace可以存在多个集群，因为一个项目的namespace是一致的，不管是哪个环境，所以也是多对多

**Comment by ssrshz** [comment]
> > @ssrshz 你能描述下整个链路么 环境-> 区域 -> 集群 -> namespace -> node 之间的关系 是多对多还是1对多
> 
> 是这样的，我们目前的环境可以分布在多个区域，比如测试环境，在上海办公室，北京办公室都存在，命名都是test
> 
> 所以环境与区域是多对多。
> 
> 区域里又可以包括个集群，而集群只能位于一个区域，区域与集群之间是一对多
> 
> 集群可以包括多个namespace，namespace可以存在多个集群，因为一个项目的namespace是一致的，不管是哪个环境，所以也是多对多

实际上，在建立模型关系的时候，如果支持多个字段组合建立关系，那就不存在多对多关系了。有点类似数据库的联合唯一索引

**Comment by pycook** [comment]
@ssrshz 已基本实现，不过这种关系的定义要在使用cmdb的时候建立好，如果后面再变更，处理当前的关系会比较复杂

**Comment by ssrshz** [comment]
> @ssrshz 已基本实现，不过这种关系的定义要在使用cmdb的时候建立好，如果后面再变更，处理当前的关系会比较复杂

太强了！确实如此，维护会复杂点，但模型关系更直观，更符合现实世界的建模，另外最大的好处是，每层模型可以独立变化，可维护性很好，而cmdb最大的负担有时候恰恰是维护代价。
