### ISSUE TITLE
新定义模型侧边栏不展示，接口数据里有新加的数据

### ISSUE THREAD

**Issue by lxyqwer** [veops/cmdb#219]
/api/v0.1/ci_types
![image](https://github.com/veops/cmdb/assets/30629682/9015d892-902e-41fd-9a6e-049aa3003ce9)

**Comment by lxyqwer** [comment]
重启 redis
 cmdb-init-acl
 cmdb-init-cache
然后又新加了一个模型，其他的竟然莫名其妙跟着一起出来了，就这样好了
 celery -A celery_worker.celery worker -E -Q acl_async会报一段错
![image](https://github.com/veops/cmdb/assets/30629682/80b58e9b-e475-41fa-a782-c0d74e4d86fa)

**Comment by pycook** [comment]
你这个根本原因还是acl worker没刷缓存 ，为啥会好的原因也是因为执行了cmdb-init-acl
celery worker的异常我尝试fix了下 你可以用最新master代码试试看 有异常再report
