### ISSUE TITLE
删除关系时报错bug

### ISSUE THREAD

**Issue by ssrshz** [veops/cmdb#220]
报错：服务端未知错误，请联系管理员

<img width="590" alt="image" src="https://github.com/veops/cmdb/assets/19809226/777210d2-daf1-40da-bd4d-1359adb5dbd7">

<img width="624" alt="image" src="https://github.com/veops/cmdb/assets/19809226/1195a9e7-83b4-4fb1-a378-83e56301f8cd">

<img width="595" alt="image" src="https://github.com/veops/cmdb/assets/19809226/f5d52c33-dfd3-44a5-a9f6-2b82f27f1ba0">

**Comment by wang-liang0615** [comment]
已fix，https://github.com/veops/cmdb/pull/224
