### ISSUE TITLE
用户新增&&授权展示异常

### ISSUE THREAD

**Issue by lxyqwer** [veops/cmdb#221]
1、ACL->用户管理：新增用户成功后，新增的用户不显示，必须刷新页面后才显示
2、资源数据->授权->授权用户/部门：选择一个新增的用户，所有新增用户和cmdb_agent 都会被选择
![image](https://github.com/veops/cmdb/assets/30629682/34603a6d-0dd4-47ce-a840-f4c5e17ce983)

**Comment by wang-liang0615** [comment]
前端acl相关已fix，https://github.com/veops/cmdb/pull/223

**Comment by simontigers** [comment]
授权选择用户时，会有多个用户被选择的问题已fix, #225
