### ISSUE TITLE
资源数据分页异常

### ISSUE THREAD

**Issue by lxyqwer** [veops/cmdb#228]
![image](https://github.com/veops/cmdb/assets/30629682/4fad9672-eb05-4dd2-ad45-f445244890d8)
实地数据只有 8 条，显示 56 条，当分页大小为 50时，第一页只展示两条，api：/api/v0.1/ci/s?q=_type:60&count=50&page=1
![image](https://github.com/veops/cmdb/assets/30629682/dfb3ae2f-ad44-4ff0-b7a0-37b60101c00d)

**Comment by pycook** [comment]
@lxyqwer 这个不是前端问题 是后端返回的总数是56，要么db里存在了脏数据，要么是缓存没同步导致的，你执行下flask cmdb-init-cache 同步缓存试试

**Comment by lxyqwer** [comment]
> @lxyqwer 这个不是前端问题 是后端返回的总数是56，要么db里存在了脏数据，要么是缓存没同步导致的，你执行下flask cmdb-init-cache 同步缓存试试

![image](https://github.com/veops/cmdb/assets/30629682/b009a69c-603e-47fa-a9c1-e176114329a4)
定义了一个整数类型的属性，插入数据，我这边有八条这样数据，例如数字731709964288，接口返回{'message': 'list indices must be integers or slices, not str'}，查询时页面空白，接口返回numfound为 8，如果这个数字为 1，就正常。感觉和数字大小有关
![image](https://github.com/veops/cmdb/assets/30629682/bb44689e-de1f-4cff-95e0-6e7438620cc7)

**Comment by lxyqwer** [comment]
> @lxyqwer 这个不是前端问题 是后端返回的总数是56，要么db里存在了脏数据，要么是缓存没同步导致的，你执行下flask cmdb-init-cache 同步缓存试试
https://cmdb.veops.cn/cmdb/instances/types/42 以复现
![image](https://github.com/veops/cmdb/assets/30629682/1e049c74-9e27-437f-8422-f3a506a8c460)

**Comment by pycook** [comment]
@lxyqwer 你新建这个test的值是多少，然后导致出现numfound=1的情况。我复现看看，我试了个你这个数字，只是报错，并没影响到numfound

**Comment by lxyqwer** [comment]
> @lxyqwer 你新建这个test的值是多少，然后导致出现numfound=1的情况。我复现看看，我试了个你这个数字，只是报错，并没影响到numfound
数字: 111111111111

![image](https://github.com/veops/cmdb/assets/30629682/ba8034ab-dd55-4b71-9912-44dee6b9ac21)

**Comment by pycook** [comment]
已复现，尽快修复，感谢反馈

**Comment by pycook** [comment]
@lxyqwer #230 已经fix了 但是目前的脏数据可能需要在db的c_cis表里清理了
