### ISSUE TITLE
[Bug]: 数据资源中的table，通过鼠标拖拽字段重新排序后，刷新又变回来了

### ISSUE THREAD

**Issue by jovicisco** [veops/cmdb#237]
### This bug is related to UI or API?

UI

### What happened?

数据资源中的table，通过鼠标拖拽字段重新排序后，刷新又变回来了。
通过选择字段的对话框中排序字段可以生效。

### Version

2.3.5

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
数据资源中的table，通过鼠标拖拽字段重新排序后，刷新又变回来了
```

**Comment by Selina316** [comment]
> ### Contact Details
> _No response_
> 
> ### This bug is related to UI or API?
> UI
> 
> ### What happened?
> 数据资源中的table，通过鼠标拖拽字段重新排序后，刷新又变回来了。 通过选择字段的对话框中排序字段可以生效。
> 
> ### Version
> 2.3.5
> 
> ### What browsers are you seeing the problem on?
> Chrome
> 
> ### Relevant log output
> ```shell
> 数据资源中的table，通过鼠标拖拽字段重新排序后，刷新又变回来了
> ```

拖拽table字段排序只是临时的，如果需要排序永久生效，必须通过选择字段的对话框中去更改字段顺序

**Comment by pycook** [comment]
@jovicisco 已有回复   没问题的话就close掉了
