### ISSUE TITLE
[Bug]: attributes with same name conflict in different model

### ISSUE THREAD

**Issue by rickywei** [veops/cmdb#240]
### This bug is related to UI or API?

API

### What happened?

1. create a model with attribute named update_time which type is text
2. create another model with attribute which has same name update_time but with different type datetime
3. api returns 重复的属性名 update_time

what is expected:
1. attributes with same name in different model should not be conflicting

### Version

newest

**Comment by pycook** [comment]
属性名全局唯一 这个目前不会有修改
