### ISSUE TITLE
[help wanted]: 是否有Excel表格方式导入的方式接口？

### ISSUE THREAD

**Issue by HarryHlh** [veops/cmdb#253]
### Contact Details

huanglihui192@163.com

### What is your question?

是否有Excel表格方式导入的方式接口？我没有在开源的文档介绍里面看到，不确定是否商业版本中存在此类功能。如果有的话可以邮件联系我，如果满足我们的需求不排除后续使用商业版本

### Version

newest

**Comment by ivonGwy** [comment]
开源版本本身是支持在页面上进行excel导入的，
![image](https://github.com/veops/cmdb/assets/18479008/f5104ab1-224d-4627-99b7-f8b53ff13a34)
你说的是api或是sdk方式进行导入吗？

**Comment by HarryHlh** [comment]
您好，
 可能我在github上没有表达清楚，我想通过接口的方式（api或者sdk）实现excel的导入，这个能实现吗？


在 2023年11月6日 ***@***.***> 写道：


开源版本本身是支持在页面上进行excel导入的，
 
 你说的是api或是sdk方式进行导入吗？

**Comment by ivonGwy** [comment]
理解了，这边建议写一个解析excel的脚本然后使用提供的新增CI接口进行替代。
![image](https://github.com/veops/cmdb/assets/18479008/9129657a-524b-4855-b011-78f702c639a6)
文档地址为：https://veops.cn/docs/cmdb/api/

如果需要我们提供相关帮助，可以加微信
![image](https://github.com/veops/cmdb/assets/18479008/05bbbe48-3da7-443e-83e4-8897c6c64fac)
