### ISSUE TITLE
docker部署，无法访问

### ISSUE THREAD

**Issue by Peterzhangnoise** [veops/cmdb#269]
### What is your question?

因为我本地8000端口在用，手动将dockercompose中8000改为8001，现在浏览器无法打开页面
docker ps -a查看api容器无法启动

以下是api日志
docker logs a628210cc2dd
--------------------------------------------------------
 docker-compose-wait 2.7.3
---------------------------
Starting with configuration:
 - Hosts to be waiting for: [cmdb-db:3306, cmdb-cache:6379]
 - Timeout before failure: 30 seconds 
 - TCP connection timeout before retry: 5 seconds 
 - Sleeping time before checking for hosts availability: 0 seconds
 - Sleeping time once all hosts are available: 0 seconds
 - Sleeping time between retries: 1 seconds
--------------------------------------------------------
Checking availability of cmdb-db:3306
Host cmdb-db:3306 not yet available...
Host cmdb-db:3306 is now available!
--------------------------------------------------------
Checking availability of  cmdb-cache:6379
Host  cmdb-cache:6379 is now available!
--------------------------------------------------------
docker-compose-wait - Everything's fine, the application can now start!
--------------------------------------------------------

### Version

newest

**Comment by Peterzhangnoise** [comment]
[root@confluence cmdb]# docker-compose up
[+] Building 0.0s (0/0)                                                                                                                                                                                                          docker:default
[+] Running 5/5
 ✔ Network cmdb_new      Created                                                                                                                                                                                                           0.1s 
 ✔ Container cmdb-cache  Created                                                                                                                                                                                                           0.3s 
 ✔ Container cmdb-db     Created                                                                                                                                                                                                           0.3s 
 ✔ Container cmdb-api    Created                                                                                                                                                                                                           0.1s 
 ✔ Container cmdb-ui     Created                                                                                                                                                                                                           0.1s 
Attaching to cmdb-api, cmdb-cache, cmdb-db, cmdb-ui
cmdb-cache  | 1:C 17 Nov 2023 02:59:36.728 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
cmdb-cache  | 1:C 17 Nov 2023 02:59:36.728 # Redis version=6.2.5, bits=64, commit=00000000, modified=0, pid=1, just started
cmdb-cache  | 1:C 17 Nov 2023 02:59:36.728 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
cmdb-cache  | 1:M 17 Nov 2023 02:59:36.729 * monotonic clock: POSIX clock_gettime
cmdb-cache  | 1:M 17 Nov 2023 02:59:36.729 * Running mode=standalone, port=6379.
cmdb-cache  | 1:M 17 Nov 2023 02:59:36.729 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
cmdb-cache  | 1:M 17 Nov 2023 02:59:36.729 # Server initialized
cmdb-cache  | 1:M 17 Nov 2023 02:59:36.729 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
cmdb-cache  | 1:M 17 Nov 2023 02:59:36.729 * Ready to accept connections
cmdb-db     | 2023-11-17 10:59:36+08:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.36-1debian10 started.
cmdb-db     | 2023-11-17 10:59:36+08:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
cmdb-db     | 2023-11-17 10:59:36+08:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.36-1debian10 started.
cmdb-db     | 2023-11-17T02:59:36.994081Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
cmdb-db     | 2023-11-17T02:59:36.994797Z 0 [Note] mysqld (mysqld 5.7.36) starting as process 1 ...
cmdb-db     | 2023-11-17T02:59:36.997168Z 0 [Note] InnoDB: PUNCH HOLE support available
cmdb-db     | 2023-11-17T02:59:36.997180Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
cmdb-db     | 2023-11-17T02:59:36.997183Z 0 [Note] InnoDB: Uses event mutexes
cmdb-db     | 2023-11-17T02:59:36.997186Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
cmdb-db     | 2023-11-17T02:59:36.997188Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
cmdb-db     | 2023-11-17T02:59:36.997192Z 0 [Note] InnoDB: Using Linux native AIO
cmdb-db     | 2023-11-17T02:59:36.997467Z 0 [Note] InnoDB: Number of pools: 1
cmdb-db     | 2023-11-17T02:59:36.997574Z 0 [Note] InnoDB: Using CPU crc32 instructions
cmdb-db     | 2023-11-17T02:59:36.998860Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
cmdb-db     | 2023-11-17T02:59:37.004309Z 0 [Note] InnoDB: Completed initialization of buffer pool
cmdb-db     | 2023-11-17T02:59:37.006109Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
cmdb-db     | 2023-11-17T02:59:37.017410Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
cmdb-db     | 2023-11-17T02:59:37.024471Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
cmdb-db     | 2023-11-17T02:59:37.024518Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
cmdb-db     | 2023-11-17T02:59:37.039593Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
cmdb-db     | 2023-11-17T02:59:37.040031Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
cmdb-db     | 2023-11-17T02:59:37.040039Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
cmdb-db     | 2023-11-17T02:59:37.040405Z 0 [Note] InnoDB: Waiting for purge to start
cmdb-api    | --------------------------------------------------------
cmdb-api    |  docker-compose-wait 2.7.3
cmdb-api    | ---------------------------
cmdb-api    | Starting with configuration:
cmdb-api    |  - Hosts to be waiting for: [cmdb-db:3306, cmdb-cache:6379]
cmdb-api    |  - Timeout before failure: 30 seconds 
cmdb-api    |  - TCP connection timeout before retry: 5 seconds 
cmdb-api    |  - Sleeping time before checking for hosts availability: 0 seconds
cmdb-api    |  - Sleeping time once all hosts are available: 0 seconds
cmdb-api    |  - Sleeping time between retries: 1 seconds
cmdb-api    | --------------------------------------------------------
cmdb-api    | Checking availability of cmdb-db:3306
cmdb-api    | Host cmdb-db:3306 not yet available...
cmdb-db     | 2023-11-17T02:59:37.090665Z 0 [Note] InnoDB: 5.7.36 started; log sequence number 13965974
cmdb-db     | 2023-11-17T02:59:37.091581Z 0 [Note] Plugin 'FEDERATED' is disabled.
cmdb-db     | 2023-11-17T02:59:37.091927Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
cmdb-db     | 2023-11-17T02:59:37.103118Z 0 [Note] InnoDB: Buffer pool(s) load completed at 231117 10:59:37
cmdb-db     | 2023-11-17T02:59:37.103326Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
cmdb-db     | 2023-11-17T02:59:37.103355Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
cmdb-db     | 2023-11-17T02:59:37.103365Z 0 [Warning] A deprecated TLS version TLSv1 is enabled. Please use TLSv1.2 or higher.
cmdb-db     | 2023-11-17T02:59:37.103375Z 0 [Warning] A deprecated TLS version TLSv1.1 is enabled. Please use TLSv1.2 or higher.
cmdb-db     | 2023-11-17T02:59:37.104841Z 0 [Warning] CA certificate ca.pem is self signed.
cmdb-db     | 2023-11-17T02:59:37.104927Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
cmdb-db     | 2023-11-17T02:59:37.106182Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
cmdb-db     | 2023-11-17T02:59:37.106277Z 0 [Note] IPv6 is available.
cmdb-db     | 2023-11-17T02:59:37.106295Z 0 [Note]   - '::' resolves to '::';
cmdb-db     | 2023-11-17T02:59:37.106344Z 0 [Note] Server socket created on IP: '::'.
cmdb-db     | 2023-11-17T02:59:37.113675Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
cmdb-db     | 2023-11-17T02:59:37.132248Z 0 [Note] Event Scheduler: Loaded 0 events
cmdb-db     | 2023-11-17T02:59:37.132659Z 0 [Note] mysqld: ready for connections.
cmdb-db     | Version: '5.7.36'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
cmdb-ui     | envsubst: error while reading "standard input": Is a directory
cmdb-ui     | 2023/11/17 10:59:37 [notice] 8#8: using the "epoll" event method
cmdb-ui     | 2023/11/17 10:59:37 [notice] 8#8: nginx/1.21.4
cmdb-ui     | 2023/11/17 10:59:37 [notice] 8#8: built by gcc 10.3.1 20210424 (Alpine 10.3.1_git20210424) 
cmdb-ui     | 2023/11/17 10:59:37 [notice] 8#8: OS: Linux 3.10.0-1160.el7.x86_64
cmdb-ui     | 2023/11/17 10:59:37 [notice] 8#8: getrlimit(RLIMIT_NOFILE): 1048576:1048576
cmdb-ui     | 2023/11/17 10:59:37 [notice] 8#8: start worker processes
cmdb-ui     | 2023/11/17 10:59:37 [notice] 8#8: start worker process 9
cmdb-ui     | 2023/11/17 10:59:37 [notice] 8#8: start worker process 10
cmdb-ui     | 2023/11/17 10:59:37 [notice] 8#8: start worker process 11
cmdb-ui     | 2023/11/17 10:59:37 [notice] 8#8: start worker process 12
cmdb-api    | Host cmdb-db:3306 is now available!
cmdb-api    | --------------------------------------------------------
cmdb-api    | Checking availability of  cmdb-cache:6379
cmdb-api    | Host  cmdb-cache:6379 is now available!
cmdb-api    | --------------------------------------------------------
cmdb-api    | docker-compose-wait - Everything's fine, the application can now start!
cmdb-api    | --------------------------------------------------------
cmdb-db     | 2023-11-17T02:59:38.050967Z 2 [Note] Got an error reading communication packets
cmdb-db     | 2023-11-17T02:59:39.628814Z 4 [Note] Aborted connection 4 to db: 'cmdb' user: 'cmdb' host: '172.27.0.4' (Got an error reading communication packets)
cmdb-db     | 2023-11-17T02:59:39.628870Z 3 [Note] Aborted connection 3 to db: 'cmdb' user: 'cmdb' host: '172.27.0.4' (Got an error reading communication packets)
cmdb-db     | 2023-11-17T02:59:41.117954Z 5 [Note] Aborted connection 5 to db: 'cmdb' user: 'cmdb' host: '172.27.0.4' (Got an error reading communication packets)
cmdb-db     | 2023-11-17T02:59:45.615322Z 7 [Note] Aborted connection 7 to db: 'cmdb' user: 'cmdb' host: '172.27.0.4' (Got an error reading communication packets)
cmdb-db     | 2023-11-17T02:59:47.189260Z 8 [Note] Aborted connection 8 to db: 'cmdb' user: 'cmdb' host: '172.27.0.4' (Got an error reading communication packets)
cmdb-db     | 2023-11-17T02:59:48.867795Z 9 [Note] Aborted connection 9 to db: 'cmdb' user: 'cmdb' host: '172.27.0.4' (Got an error reading communication packets)
cmdb-db     | 2023-11-17T02:59:48.876475Z 6 [Note] Aborted connection 6 to db: 'cmdb' user: 'cmdb' host: '172.27.0.4' (Got an error reading communication packets)
cmdb-api exited with code 1

**Comment by pycook** [comment]
@Peterzhangnoise 你执行过 `docker-compose down -v`  么 ？

**Comment by Peterzhangnoise** [comment]
执行过

pycook ***@***.***> 于 2023年11月17日周五 下午1:57写道：

**Comment by Peterzhangnoise** [comment]
已解决

**Comment by Maximus48p** [comment]
> 已解决

What was the solution? Having the same problem.
解决办法是什么？ 遇到同样的问题
