### ISSUE TITLE
[Bug]: 批量导入时，点击取消，还会自己导入一段时间，相当于后台没有停止这个导入进程

### ISSUE THREAD

**Issue by ChineseLiusir** [veops/cmdb#304]
### What happened?

批量导入时，点击取消，还会自己导入一段时间，相当于后台没有停止这个导入进程

### Version

newest

**Comment by wang-liang0615** [comment]
fix，https://githubfast.com/veops/cmdb/pull/306

**Comment by pycook** [comment]
@ChineseLiusir v2.3.8验证下
