### ISSUE TITLE
[Feature]: 批量导入时，属性预定义值是否能直接带到模板内

### ISSUE THREAD

**Issue by NemoAllenZ** [veops/cmdb#332]
### feature is related to UI or API aspects?

API

### What is your advice?

批量导入时，对于有预定义值的属性，希望能把预定义值填入模板内，提示用户上传时在预定义值内选择填入

### Version

2.3.8

**Comment by NemoAllenZ** [comment]
![image](https://github.com/veops/cmdb/assets/56422553/0060e4f2-dd9c-4431-a4ee-a8a72cf8fbed)
比如区域这个属性有预定义值，如果在导入模板中带入预定义值，用户上传时就可以直接填上预定义值其中一个，避免填错上传失败
![image](https://github.com/veops/cmdb/assets/56422553/11504be4-282a-4582-9409-28ac0c53a284)

**Comment by wang-liang0615** [comment]
https://github.com/veops/cmdb/pull/342
