### ISSUE TITLE
插入具体数据的时候好像不能配置关联关系？

### ISSUE THREAD

**Issue by gothack329** [veops/cmdb#37]
目前好像模型的关联可以建立好，但是实体之间的关系好像不能配置，比如从demo里新建了一个产品线，没法和具体的事业部之间做关联么

**Comment by pycook** [comment]
@gothack329 目前UI上不支持实例间的关系增删改，在TODO list里。目前这个只能调用API

**Comment by pycook** [comment]
这个目前在2.3.0版本里，CI详情页里的关系里可以增删
<img width="472" alt="image" src="https://github.com/veops/cmdb/assets/4044021/66f3ffbd-df62-49d1-b12b-a73fd82b2412">
