### ISSUE TITLE
[Bug]: 修改密码后系统假死

### ISSUE THREAD

**Issue by engin-zhou** [veops/cmdb#383]
### What happened?

在个人中心里，修改新的密码后，系统无法进入，登上很长一段时间后才能用初始密码登录，这个模块是不是无效的？

### Version

newest

**Comment by Selina316** [comment]
![image](https://github.com/veops/cmdb/assets/39409446/ca6b5716-7bae-4b27-aefa-e861775e30dc)
请问系统的认证设置有专门配置过吗

**Comment by Selina316** [comment]
请问系统的认证设置有专门配置过吗?
![image](https://github.com/veops/cmdb/assets/39409446/16a71c10-da2e-4bd6-a165-fb2aec1ffaa1)

**Comment by engin-zhou** [comment]
没有，刚弄好的系统



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月15日(周一) 下午2:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [veops/cmdb] [Bug]: 修改密码后系统假死 (Issue #383)




 
image.png (view on web)
 请问系统的认证设置有专门配置过吗

**Comment by Selina316** [comment]
重置密码提示成功后，立马就无法使用系统了吗？或则有没有什么报错信息，如果有请提供一下截图

**Comment by engin-zhou** [comment]
没有消息，立马挂掉，过一阵子才能打开，而且密码没变。在哪个日志文件里会有记录？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月15日(周一) 下午5:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [veops/cmdb] [Bug]: 修改密码后系统假死 (Issue #383)




 
重置密码提示成功后，立马就无法使用系统了吗？或则有没有什么报错信息，如果有请提供一下截图

**Comment by Selina316** [comment]
@engin-zhou  api容器里的logs目录下
