### ISSUE TITLE
[Bug]: 模型属性中预定义值超过10个，批量导入中下载的模型模板在excel中不显示下拉框属性

### ISSUE THREAD

**Issue by wyx19** [veops/cmdb#384]
### This bug is related to UI or API?

UI, API

### What happened?

模型属性中预定义值超过10个，批量导入中下载的模型模板在excel中不显示下拉框属性

### Version

2.3.10

### What browsers are you seeing the problem on?

Chrome

**Comment by Selina316** [comment]
请注意，受excel本身的限制，单个下拉框限制了最多255个字符，如果超过255个字符，我们不会在模板中设置该属性的下拉选项。请确认一下您的下拉选项总字符数是否超过255个字符
