### ISSUE TITLE
[Feature]: ci关系维护可以考虑字段关联，自动进行维护，不需要人工维护。推荐思路-模型先关联然后字段再关联，增删改实例的时候可以自动维护实例关系

### ISSUE THREAD

**Issue by dotachuanqi** [veops/cmdb#389]
### What is your advice?

everyone wants this feature!

### Version

newest

**Comment by pycook** [comment]
本身就支持字段关联，只不过这个字段是模型的主键字段而已，使用方法${模型名}.{模型属性}

**Comment by Selina316** [comment]
[v2.4.2](https://github.com/veops/cmdb/releases/tag/2.4.2)后的版本已支持属性关联功能
