### ISSUE TITLE
Python 3.8下不能运行和sql文件无法直接导入的问题

### ISSUE THREAD

**Issue by AngrygrayWolf** [veops/cmdb#39]
## 高于python 3.8，无法使用低版本的werkzeug。会报以下错误：

`TypeError: required field "type_ignores" missing from Module`
 建议修改 `requirements.txt`： 将werkzeug依赖版本修改为： `werkzeug >= 0.15.5`

##  sql文件无法直接导入mariadb 10.4中。

怀疑使用navicat导出的语句在sql终端下不能很好的兼容（使用navicat可以正常导入）。建议作者在readme中给一下mysql版本。

**Comment by pycook** [comment]
#38 已经fix

**Comment by YoungDonald** [comment]
mariadb导入SQL也会出错，还是推荐使用mysql
