### ISSUE TITLE
创建模型多对多关联关系时提示多对多关联已存在？

### ISSUE THREAD

**Issue by crezy8** [veops/cmdb#400]
### Contact Details

itjohnsonxu@gmail.com

### What is your question?

在测试的几款cmdb中最趁手的就是维易cmdb，是足够了解运维的产品，使用过程也遇到了一些问题想请教。
我想借助模型之间的关联关系创一个以应用为中心的资源拓扑，此时就有一个问题，就是模型关联时的约束关系为什么只允许存在一个多对多关系？比如应用和虚拟机多对多关联后就无法再创建应用多对多关联其他模型，会提示已存在多对多关联，这个是出于什么考虑。

在我的是用场景中，应用和服务器，应用和数据库都是多对多关系，因为服务器复用，一个服务器会部署多个应用，在一对多的关系中服务器只能关联一个应用，数据库也是同理，这种多对多关系的共享配置我想也是比较常见的。
期待你们的答复！

### Version

newest

**Comment by pycook** [comment]
@crezy8 多对多本身不复杂，但是如果应用在服务树上就会比较复杂, 这个限制会在下个版本取消！

**Comment by pycook** [comment]
#401
