### ISSUE TITLE
[Feature]: 希望增加枚举类型字段

### ISSUE THREAD

**Issue by lxyqwer** [veops/cmdb#408]
![image](https://github.com/veops/cmdb/assets/30629682/55d076fd-3862-4067-a474-e5af9f86c86d)

**Comment by pycook** [comment]
枚举类似于当前的预定义值

**Comment by lxyqwer** [comment]
> 当前的预定义值

【预定义值】是在哪配置？

**Comment by lxyqwer** [comment]
预定义值 没有 [{k1: v1},{k2: v2}]这种，只能是一个值

**Comment by lxyqwer** [comment]
预定义值 没有 [{k1: v1},{k2: v2}]这种，只能是一个值

**Comment by pycook** [comment]
https://github.com/veops/cmdb/releases/tag/v2.4.11 已支持
