### ISSUE TITLE
[Bug]:  模型设置唯一标识为自增ID，添加CI的时候提示主键字段缺失

### ISSUE THREAD

**Issue by julyxiong** [veops/cmdb#409]
### This bug is related to UI or API?

UI

### What happened?

模型配置：
![图片](https://github.com/veops/cmdb/assets/32185365/1e789e62-9e00-40fa-89da-1163afc8b4e0)

UI界面添加CI提示自增ID缺失
![图片](https://github.com/veops/cmdb/assets/32185365/8d25a86f-a689-4705-92cc-8820094c4124)

### Version

2.3.11

**Comment by julyxiong** [comment]
一些计算属性的字段好像也不能作为模型的唯一标识

**Comment by pycook** [comment]
#391 自增ID可作为唯一标识! 在v2.3.12版本已经支持
https://github.com/veops/cmdb/releases/tag/2.3.12

**Comment by lxyqwer** [comment]
> #391 自增ID可作为唯一标识! 在v2.3.12版本已经支持 https://github.com/veops/cmdb/releases/tag/2.3.12

意思是唯一标识在录入数据的时候可以不填写，它会自增id填充吗？这个怎么使用呢？
