### ISSUE TITLE
[Bug]:  更新版本后，创建CI提示无效的值

### ISSUE THREAD

**Issue by julyxiong** [veops/cmdb#410]
### What happened?

![图片](https://github.com/veops/cmdb/assets/32185365/e9d0f9ef-22c3-45b2-a6da-62cd43d20473)

![图片](https://github.com/veops/cmdb/assets/32185365/e7d7c3ab-bae9-4c7e-aee4-a5ae457569e6)

### Version

newest

**Comment by julyxiong** [comment]
docker部署，
2.3.11 - > 2.3.12

**Comment by Selina316** [comment]
该属性限制为 唯一，值重复肯定会报错的
