### ISSUE TITLE
[Bug]:  属性配置唯一，使用批量导入出现重复值

### ISSUE THREAD

**Issue by julyxiong** [veops/cmdb#412]
### What happened?

CI属性配置唯一，使用导入功能，会出现重复的值。
截图中的  w_domain 字段出现重复。

测试还发现，自增ID导入的时候也会出现重复ID。

![图片](https://github.com/veops/cmdb/assets/32185365/9098d672-797c-4b57-af9c-135d309228da)
![图片](https://github.com/veops/cmdb/assets/32185365/208342c1-bc3b-4de0-abbd-cc0c02cfa38c)

![图片](https://github.com/veops/cmdb/assets/32185365/85c84635-dbc1-4995-ba0a-825b2b620a34)

### Version

2.3.12

### What browsers are you seeing the problem on?

Chrome

**Comment by julyxiong** [comment]
自增编号的字段，在 CI_TYPE 中已经删除，但是 UI 界面还是有展示。这也算一个问题吧。

**Comment by pycook** [comment]
@julyxiong #413 已经fix你描述的这2个问题
