### ISSUE TITLE
[Bug]: 关系表格展示问题

### ISSUE THREAD

**Issue by lxyqwer** [veops/cmdb#419]
### This bug is related to UI or API?

UI

### What happened?

![image](https://github.com/veops/cmdb/assets/30629682/a4a3136b-8d21-42b9-8516-52a5c023a97a)
没有分页，也没有滑动窗口，只能看到一部分数据

### Version

2.3.12

### What browsers are you seeing the problem on?

Chrome

**Comment by pycook** [comment]
version: 2.3.13 已经fix
