### ISSUE TITLE
[Bug]: 模型配置唯一校验错误

### ISSUE THREAD

**Issue by lxyqwer** [veops/cmdb#421]
### This bug is related to UI or API?

API

### What happened?

ci配置模型属性并配置为唯一校验，当把这个模型属性删除后，再配置唯一校验弹窗不会出现，/api/v0.1/ci_types/46/unique_constraint接口返回的还是已被删除的属性
![image](https://github.com/veops/cmdb/assets/30629682/0d56f60c-c149-4964-bb3c-9c4ac6743a28)

### Version

2.3.12

### What browsers are you seeing the problem on?

Chrome

**Comment by Selina316** [comment]
version: 2.3.13 已经fix

**Comment by Selina316** [comment]
version: 2.3.13 已经fix @lxyqwer
