### ISSUE TITLE
[Bug]: Bypass upload file restrict

### ISSUE THREAD

**Issue by nevercodecorrect** [veops/cmdb#428]
### What happened?

In code [here](https://github.com/veops/cmdb/blob/4117cf87ec27c080d9619a4583f0fa5c5a2f320a/cmdb-api/api/lib/common_setting/upload_file.py#L15), the file filtering is based on the user provided filename. User could manipulate the MIME type to bypass it. Using magic code to check if it is xls/xlsx file would be better.

### Version

newest

**Comment by simontigers** [comment]
#430 check ext with magic
