### ISSUE TITLE
[Bug]: 管理员账号,我的订阅为0

### ISSUE THREAD

**Issue by taoyang987** [veops/cmdb#434]
### Contact Details

taoyang987@gmail.com

### This bug is related to UI or API?

UI

### What happened?

默认自带的管理员,不知道怎么了我的订阅变为0
![image](https://github.com/veops/cmdb/assets/872386/acb7c58e-bd85-4bc4-9e9b-f6dccfad8536)
其他地方日志全都翻过了,没有气场.发现只有浏览器有js报错
<img width="783" alt="image" src="https://github.com/veops/cmdb/assets/872386/a406efad-0488-4185-854d-7ca5fb4bf3a8">

### Version

newest

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by Selina316** [comment]
@taoyang987  这里能麻烦点进去并给一下报错代码的截图吗？
![image](https://github.com/veops/cmdb/assets/39409446/3da5a694-bab2-4d8c-8e85-fd73fb6d4e4d)

**Comment by taoyang987** [comment]
@Selina316 具体要怎么截图吗?,麻烦加我wx吧,我再把数据库传给你 ,
wx:
taoyang987
这个bug对我来说现在使用比较重要.

**Comment by taoyang987** [comment]
[cmdb.sql.zip](https://github.com/veops/cmdb/files/14751810/cmdb.sql.zip)
我把数据库导出来了
默认的admin 123456登录就能看到

**Comment by Selina316** [comment]
初步定位是我的订阅页面/api/v0.1/preference/ci_types2?instance=true&tree=true 接口中返回的id=41的模型在/api/v0.1/preference/ci_types?instance=true&tree=true中没有返回导致的 @pycook

**Comment by taoyang987** [comment]
![image](https://github.com/veops/cmdb/assets/872386/8f9cf4fa-3bc2-4d2b-9d17-5caef43fb9a9)
但是我用其他管理员账号,发现id=41的模型也在其中
<img width="694" alt="image" src="https://github.com/veops/cmdb/assets/872386/e37ce0d3-a50a-4b8a-9420-10b44f307b1e">

**Comment by Selina316** [comment]
您直接把备份的数据导入到一个初始的环境 这个初始环境的缓存和权限都不是基于你这个备份的sql构建的 ，建议不要再这么操作
