### ISSUE TITLE
[Bug]: 批量导入:模型关联功能不生效

### ISSUE THREAD

**Issue by taoyang987** [veops/cmdb#439]
### Contact Details

taoyang987@gmail.com

### This bug is related to UI or API?

API

根据githu上最新的代码docker-compose部署的
### What happened?

模型下载时我勾选了
<img width="814" alt="image" src="https://github.com/veops/cmdb/assets/872386/a5faab4e-cbe2-43fd-9679-68db266d17f1">
下载的模版中有了相应字段:
<img width="407" alt="image" src="https://github.com/veops/cmdb/assets/872386/79fa1368-0790-46e1-b0e9-86dafeb6c35c">
填写好上传,过程一直都是提示成功.
但是发现最后没有关联成功,还是得去手动选择关联

### Version

newest

**Comment by Selina316** [comment]
数据库和环境是什么关系？一对多还是一对一？ @taoyang987

**Comment by taoyang987** [comment]
这次我用全新的环境试了,数据库删除,docker-compose重新创建全都是初始的数据,没动过.产品2是我导入的
<img width="315" alt="image" src="https://github.com/veops/cmdb/assets/872386/6604ef0e-8d58-48f0-9c4f-1edc939b130a">

**Comment by taoyang987** [comment]
用我试了v2.3.12 693ae4f正常的
但是最新的v2.3.13就是有这个bug
docker-compose 初始化后,直接上传附件,
[cmdb-物理机-20240326173231.xlsx](https://github.com/veops/cmdb/files/14756312/cmdb-.-20240326173231.xlsx)
v2.3.12 会出现第二台物理机
![image](https://github.com/veops/cmdb/assets/872386/9fa35c70-8ef3-4e4d-aa07-26b3b0957c50)

**Comment by pycook** [comment]
2.4.1 版本修复此问题了，2.3.13版本存在这个问题
