### ISSUE TITLE
[help wanted]: 列表表头顺序调整后如何保存?

### ISSUE THREAD

**Issue by taoyang987** [veops/cmdb#440]
### Contact Details

taoyang987@gmail.com

### What is your question?

<img width="1424" alt="image" src="https://github.com/veops/cmdb/assets/872386/125f056f-86e0-4c5b-8e98-159a32c5ef39">
请问下,列表表头顺序调整后怎么保存吗?
可以重新排列,但是一刷新就又变成这样了≥

<img width="1129" alt="image" src="https://github.com/veops/cmdb/assets/872386/266931b4-3c4c-4193-88cf-6ce9b9a7b0a7">
跟模型里的顺序看起来也一点没关联

### Version

newest

**Comment by Selina316** [comment]
@taoyang987 
![image](https://github.com/veops/cmdb/assets/39409446/4bce631d-b648-4675-bedd-7f44f9ba0158)

**Comment by Selina316** [comment]
可以参考文档：https://veops.cn/docs/docs/cmdb/basic/cmdb_check
