### ISSUE TITLE
[Bug]: 导入模型报错

### ISSUE THREAD

**Issue by taoyang987** [veops/cmdb#441]
### Contact Details

taoyang987@gmail.com

### What happened?

把所有模型导出json,再导入时提示报错
![image](https://github.com/veops/cmdb/assets/872386/6d538aff-d3ea-46fc-85ab-0ffaa31549c4)
![image](https://github.com/veops/cmdb/assets/872386/25c92e92-165a-4c63-b6bf-a3bf522faf5d)
<img width="856" alt="image" src="https://github.com/veops/cmdb/assets/872386/7d58c1ab-229f-447d-8b72-3a6b9d2bbb64">
去json文件里"inherited'相关字段删除再导入就好了
<img width="360" alt="image" src="https://github.com/veops/cmdb/assets/872386/ea047c91-49d5-4300-aa0b-f40b9331d962">

### Version

newest

**Comment by pycook** [comment]
#442 @taoyang987

**Comment by taoyang987** [comment]
用我试了v2.3.12 693ae4f正常的
但是最新的v2.3.13就是有这个bug
docker-compose 初始化后,直接上传附件,
[cmdb-物理机-20240326173231.xlsx](https://github.com/veops/cmdb/files/14756312/cmdb-.-20240326173231.xlsx)
v2.3.12 会出现第二台物理机
<img width="1191" alt="image" src="https://github.com/veops/cmdb/assets/872386/c0a67a51-30e8-4b51-8040-601c28acc414">
