### ISSUE TITLE
[Bug]: 数据库还原后,自定义模型不见了

### ISSUE THREAD

**Issue by taoyang987** [veops/cmdb#443]
### Contact Details

taoyang987@gmail.com

### What happened?

用navicat备份mysql数据库
<img width="477" alt="image" src="https://github.com/veops/cmdb/assets/872386/6a3b44ef-8cc6-4c23-9c82-ee4975165b51">
还原后,发现原先的模型不见了,资源数据还在

### Version

newest

**Comment by Selina316** [comment]
您是直接对db的操作，数据的查看与缓存和权限相关，备份的数据导入到一个初始的环境 这个初始环境的缓存和权限都不是基于你这个备份的sql构建的，不建议这么操作。

**Comment by taoyang987** [comment]
把redis容器重新创建就可以了
