### ISSUE TITLE
[Bug]: dockerfile db volumes是不是写错了

### ISSUE THREAD

**Issue by M0Cube** [veops/cmdb#452]
### This bug is related to UI or API?

API

### What happened?

version: '3.5'

services:
  cmdb-db:
    image: registry.cn-hangzhou.aliyuncs.com/veops/cmdb-db:2.3
    container_name: cmdb-db
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'cmdb'
      MYSQL_USER: 'cmdb'
      MYSQL_PASSWORD: '123456'
    volumes:
      - db-data:/var/lib/mysql
      - ./docs/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
      - ./docs/cmdb.sql:/docker-entrypoint-initdb.d/cmdb.sql

是不是因该写./db-data:/var/lib/mysql   还是我没理解这样做的意思

### Version

newest

### Relevant log output

```shell
不然默认第一次运行会报错 无法导入  db文件有问题
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
```

**Comment by fxiang21** [comment]
@M0Cube 
这个挂载没有问题的，不是挂载的目录，参考docker-compose.yaml的如下内容中的db-data;
volumes:
  db-data:
    driver: local
    name: cmdb_db-data
