### ISSUE TITLE
[Feature]: 资源数据希望能同步按模型分组显示

### ISSUE THREAD

**Issue by NemoAllenZ** [veops/cmdb#466]
### feature is related to UI or API aspects?

UI

### What is your advice?

当前显示订阅的资源数据，没有同步模型分组，导致订阅多了之后下拉太长，希望订阅资源数据时能同步模型的分组，并且在资源数据下拉中按模型分组显示。

（左图为资源数据菜单截图，目前的资源数据显示应该是按订阅先后顺序显示的；右图为模型分组截图，目标效果是把这些模型分组信息带入资源数据菜单，让下拉显示效果更有条理）

![image](https://github.com/veops/cmdb/assets/56422553/a43b418c-fc17-4a23-b7e3-9622aecbfa8e)        ![image](https://github.com/veops/cmdb/assets/56422553/c04d939e-810e-482b-ac52-17702055f7e1)

### Version

newest

**Comment by Selina316** [comment]
[v2.4.5](https://github.com/veops/cmdb/releases/tag/2.4.5)的版本已支持按照模型分组展示资源数据
