### ISSUE TITLE
[Bug]: 2.4.2下载模型异常

### ISSUE THREAD

**Issue by lxyqwer** [veops/cmdb#470]
### This bug is related to UI or API?

API

### What happened?

![image](https://github.com/veops/cmdb/assets/30629682/080d561d-1a28-4bd0-86c7-d638591d0a84)
下载模型后没有字段数据，2.4.1 没问题

### Version

2.4.2

**Comment by pycook** [comment]
@lxyqwer 你这个模型是继承的么  ？

**Comment by lxyqwer** [comment]
> @lxyqwer 你这个模型是继承的么 ？
感觉是数据库 sql 没更新的问题，我再看看
