### ISSUE TITLE
[help wanted]: 模型自定义图标保存路径

### ISSUE THREAD

**Issue by lxyqwer** [veops/cmdb#473]
### What is your question?

i have a question!
![image](https://github.com/veops/cmdb/assets/30629682/b6efb65e-c99e-440c-8e60-f3065ddb80dd)
模型自定义图标是保存在数据库还是本地？保存路径是什么，原数据库换了台机器部署图标 404

### Version

2.4.2

**Comment by simontigers** [comment]
最开始是存在本地的， 路径是
` api/uploaded_files/common_setting`
#292  (2023-12-11)后，
上传是保存在数据库中， 原有的本地文件，可以通过命令同步到数据库中(需要在原机器上)：
`flask common-sync-file-to-db`
