### ISSUE TITLE
[Feature]: 模型属性添加时增加中文枚举字段

### ISSUE THREAD

**Issue by lxyqwer** [veops/cmdb#492]
### What is your advice?

在录入cmdb时候我可能录入的是一个int，但int是有意义的，例如1代表运行，2代表关机，在模型增加属性的时候可以有枚举输入框

### Version

newest

**Comment by lxyqwer** [comment]
这个样在第三方系统调用的时候，就可以拉模型的这个字段读取中文解析

**Comment by pycook** [comment]
https://github.com/veops/cmdb/releases/tag/v2.4.11
