### ISSUE TITLE
[Bug]: 唯一检验异常

### ISSUE THREAD

**Issue by lxyqwer** [veops/cmdb#503]
### What happened?

在a模型新增一个f1属性，不设置唯一属性，在模型的唯一校验把这个f1属性加进去，我在b模型导入这个f1属性。我用b模型创建一条数据并填写f1属性，然后在a模型创建一条数据并设置f1属性与前面a模型录入f1的数据一样时，会触发唯一检验问题

### Version

2.4.2

**Comment by pycook** [comment]
fixed in #505
