### ISSUE TITLE
[help wanted]: 模型触发器-日期属性没有提送消息

### ISSUE THREAD

**Issue by lxyqwer** [veops/cmdb#504]
### What is your question?

![image](https://github.com/veops/cmdb/assets/30629682/d5d8840c-2b12-47e8-a5c1-8fa9d14cf49f)
1、配置后时到了提前的天数后是每天提醒还是只提醒一次
2、这个功能需不需其他组件，还是只是cmdb的功能

### Version

2.4.2

**Comment by pycook** [comment]
你可以看看后台管理->操作审计里的触发历史  api服务里flask cmdb-trigger 这个要开着
