### ISSUE TITLE
[Feature]: 页面体验优化

### ISSUE THREAD

**Issue by dengpei89** [veops/cmdb#506]
### Contact Details

dengpp@300624.cn

### feature is related to UI or API aspects?

UI

### What is your advice?

![image](https://github.com/veops/cmdb/assets/26969979/c7727ddc-0d0a-4246-9180-4f09603979a6)
1、建议在模型关系中，框内支持搜索后选择，手动输入容易输错

![image](https://github.com/veops/cmdb/assets/26969979/cdcbe8fa-b238-4420-b93a-f11e2126e1b2)
2、新建页面时，这里需要点击蓝色按钮才能关闭，建议新增在其他空白点击时也能关闭

### Version

newest

**Comment by pycook** [comment]
1. 接受
2. 用户在输入大量数据后不小心误点空白地方关闭了窗口，填的数据也会被销毁，不是一个好的体验
