### ISSUE TITLE
[Feature]: 项目缺少一个可以直观导出instances间关系的功能

### ISSUE THREAD

**Issue by thexqn** [veops/cmdb#518]
### feature is related to UI or API aspects?

UI, API

### What is your advice?

目前该项目缺少一个可以直观导出instances间关系的功能，具体描述如下：
假如项目中有如下两个CI：
- 应用
- 物理机

他们的关系是：一个应用可以部署在多个物理机上，即传统的1对多关系。
在实际工作中，经常需要导出两个CI所属的instances间的关系，具体如下表：
<table>
    <tr>
        <td colspan="2">应用</td>
        <td colspan="2">物理机</td>
    </tr>
    <tr>
        <td>应用名称</td>
        <td>应用负责人</td>
        <td>内网IP</td>
        <td>规格</td>
    </tr>
    <tr>
        <td>APP1</td>
        <td>张三</td>
        <td>192.168.1.1</td>
        <td>高性能型</td>
    </tr>
    <tr>
        <td>APP1</td>
        <td>张三</td>
        <td>192.168.1.2</td>
        <td>高性能型</td>
    </tr>
    <tr>
        <td>APP2</td>
        <td>张三</td>
        <td>192.168.1.3</td>
        <td>高性能型</td>
    </tr>
</table>
现有的“资源搜索”模块中具备多表查询的功能，根据公众号推送的文章来看，主要是为了让多种同属性的资源能够在一个页面中展示，并不能很好的解决不同种（即有1对多关系，多对多关系）的数据导出需求。
现尝试编写这部分需求的代码，初步的设想是在现有的“资源搜索”下，增加一个“并集查询”的页面，想问问这个项目的管理方是否会接受这个需求，如果接受我再尝试能不能写出来，现在项目的代码水平很高，我不确定我能不能写出满足要求的代码。

### Version

newest

**Comment by pycook** [comment]
是个好的应用场景，我们迭代完当前计划的功能之后，会考虑加进来，当然也欢迎你尝试
