### ISSUE TITLE
[Bug]: CI拓扑展开异常

### ISSUE THREAD

**Issue by sepultra** [veops/cmdb#530]
### This bug is related to UI or API?

UI

### What happened?

当前维护的模型关系为：机房 -> 机柜 -> 物理机
打开物理机CI关系拓扑，可以正常展示物理机CI关联的机柜CI，但通过机柜CI想要再往上展开看关联的机房CI没有反应
该情况在关联了同样机柜的物理机CI上出现，其它的物理机CI展示关系拓扑正常

通过简单debug，发现加载拓扑的时候，就将模型ID标记为已经存在的实例ID（exsited_ci），刚好物理机模型的模型ID=5，存在问题的机柜关联的机房CI也是ID=5，考虑是通过exsited_ci变量判断该机房CI已实例化了Node，所以没有再生成Node展示了

### Version

2.4.3

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
butterflies error: can not connect edge. link sourceNodeId:5;link targetNodeId:61
```

**Comment by LHRUN** [comment]
已修复 #532
