### ISSUE TITLE
[Bug]: 模型配置中新增CI模型错误

### ISSUE THREAD

**Issue by abelit** [veops/cmdb#536]
### What happened?

A bug happened!

### Version

newest

**Comment by pycook** [comment]
不理解你的提问

**Comment by abelit** [comment]
> 不理解你的提问
版本： cmdb: 2.4.5

问题：
我在“模型配置”那里添加模型，无论在哪个组添加，都不会立即显示在模型组那里，需要刷新浏览器，然后模型都在其他组中显示，无法正常添加模型到对应的组。
如下是截图信息，我在业务组添加模型“testhost"，需要刷新浏览器才显示，且结果显示在其他组中，还有就是添加模型窗口不会关闭，”确定“按钮一直转圈：
![Screenshot from 2024-06-14 09-10-27](https://github.com/veops/cmdb/assets/10794056/583411e4-9257-46a0-bb48-73ddae6c730c)
![Screenshot from 2024-06-14 09-11-06](https://github.com/veops/cmdb/assets/10794056/3b004191-3ffc-4b2d-b44e-7a4ccecde812)

**Comment by pycook** [comment]
问题同 #549 close这个issue了
