### ISSUE TITLE
[Bug]: 正则校验里的IP地址规则对于。等符号无效

### ISSUE THREAD

**Issue by baalchina** [veops/cmdb#538]
### What happened?

我设置了正则为ip地址：
<img width="439" alt="PixPin_2024-06-09_10-57-31" src="https://github.com/veops/cmdb/assets/3983019/e8d6fd9d-215e-4a9c-afa6-16bd455e8ae4">

新建的时候如果打的是中文的句号，没有报错，但是其他符号倒是有报错的
<img width="392" alt="PixPin_2024-06-09_10-59-21" src="https://github.com/veops/cmdb/assets/3983019/d0fb34d1-6cac-4ca0-ba7f-fd5ee3c34b77">

在批量编辑这里，无论中文符号还是其他的，都能保存成功没有报错
<img width="557" alt="PixPin_2024-06-09_10-58-24" src="https://github.com/veops/cmdb/assets/3983019/02740709-a77a-4588-98ea-e5d17cc037b5">

### Version

newest

**Comment by pycook** [comment]
问题同 #549 close这个issue了

**Comment by pycook** [comment]
问题同 #549  close这个issue了
