### ISSUE TITLE
[Bug]: 在“模型配置”中添加模型错误

### ISSUE THREAD

**Issue by abelit** [veops/cmdb#549]
### What happened?

问题1：
我在“模型配置”那里添加模型，无论在哪个组添加，都不会立即显示在模型组那里，需要刷新浏览器，然后模型都在其他组中显示，无法正常添加模型到对应的组。

问题2:
如果换个环境，又产生新的错误：
添加了，刷新浏览器也不会显示新增的模型，重启所有容器也不会显示，需要执行”docker rm -f cmdb-cache && docker volume rm cmdb_cache-data“删除缓存容器，再执行“docker-compose up -d"启动cmdb-cache才会显示新增的模型，且每次添加模型都需要这样操作才会显示。

问题1的具体信息： 如下是截图信息，我在业务组添加模型“testhost"，需要刷新浏览器才显示，且结果显示在其他组中，还有就是添加模型窗口不会关闭，”确定“按钮一直转圈：
![Screenshot from 2024-06-14 09-10-27](https://github.com/veops/cmdb/assets/10794056/c8f20c09-0e90-4641-a4e3-704622c007e0)
![Screenshot from 2024-06-14 09-11-06](https://github.com/veops/cmdb/assets/10794056/799a94d6-a1bf-41ca-bbca-0aba4056c0ba)

浏览器控制台打印有错误信息：
chunk-vendors.6d5bedf1.js:78
PUT http://172.x.x.x:8000/api/v0.1/ci_types/groups/1 net::ERR_CONNECTION_RESET
(anonymous) @ chunk-vendors.6d5bedf1.js:78
e.exports @ chunk-vendors.6d5bedf1.js:78
e.exports @ chunk-vendors.6d5bedf1.js:33
Promise.then (async)
s.request @ chunk-vendors.6d5bedf1.js:1
(anonymous) @ chunk-vendors.6d5bedf1.js:1
c @ chunk-6efe3ec5.7b9316ed.js:1
(anonymous) @ chunk-0d74f9e9.aa4c75f6.js:1
d @ chunk-vendors.6d5bedf1.js:101
(anonymous) @ chunk-vendors.6d5bedf1.js:101
(anonymous) @ chunk-vendors.6d5bedf1.js:101
r @ chunk-vendors.6d5bedf1.js:1
s @ chunk-vendors.6d5bedf1.js:1
Promise.then (async)
r @ chunk-vendors.6d5bedf1.js:1
s @ chunk-vendors.6d5bedf1.js:1
(anonymous) @ chunk-vendors.6d5bedf1.js:1
(anonymous) @ chunk-vendors.6d5bedf1.js:1
createCIType @ chunk-0d74f9e9.aa4c75f6.js:1
(anonymous) @ chunk-0d74f9e9.aa4c75f6.js:1
d @ chunk-vendors.6d5bedf1.js:101
(anonymous) @ chunk-vendors.6d5bedf1.js:101
(anonymous) @ chunk-vendors.6d5bedf1.js:101
r @ chunk-vendors.6d5bedf1.js:1
s @ chunk-vendors.6d5bedf1.js:1
(anonymous) @ chunk-vendors.6d5bedf1.js:1
(anonymous) @ chunk-vendors.6d5bedf1.js:1
(anonymous) @ chunk-0d74f9e9.aa4c75f6.js:1
u @ chunk-vendors.6d5bedf1.js:255
(anonymous) @ chunk-vendors.6d5bedf1.js:255
u @ chunk-vendors.6d5bedf1.js:1
(anonymous) @ chunk-vendors.6d5bedf1.js:1
u @ chunk-vendors.6d5bedf1.js:1
o @ chunk-vendors.6d5bedf1.js:1
s @ chunk-vendors.6d5bedf1.js:1
W @ chunk-vendors.6d5bedf1.js:1
(anonymous) @ chunk-vendors.6d5bedf1.js:1
(anonymous) @ chunk-vendors.6d5bedf1.js:1
g @ chunk-vendors.6d5bedf1.js:1
(anonymous) @ chunk-vendors.6d5bedf1.js:1
(anonymous) @ chunk-vendors.6d5bedf1.js:1
x @ chunk-vendors.6d5bedf1.js:1
validate @ chunk-vendors.6d5bedf1.js:1
validateFieldsInternal @ chunk-vendors.6d5bedf1.js:255
(anonymous) @ chunk-vendors.6d5bedf1.js:255
validateFields @ chunk-vendors.6d5bedf1.js:255
(anonymous) @ chunk-0d74f9e9.aa4c75f6.js:1
d @ chunk-vendors.6d5bedf1.js:101
(anonymous) @ chunk-vendors.6d5bedf1.js:101
(anonymous) @ chunk-vendors.6d5bedf1.js:101
r @ chunk-vendors.6d5bedf1.js:1
s @ chunk-vendors.6d5bedf1.js:1
(anonymous) @ chunk-vendors.6d5bedf1.js:1
(anonymous) @ chunk-vendors.6d5bedf1.js:1
handleSubmit @ chunk-0d74f9e9.aa4c75f6.js:1
nt @ chunk-vendors.6d5bedf1.js:7
n @ chunk-vendors.6d5bedf1.js:7
nt @ chunk-vendors.6d5bedf1.js:7
Tn.e.$emit @ chunk-vendors.6d5bedf1.js:7
handleClick @ chunk-vendors.6d5bedf1.js:255
nt @ chunk-vendors.6d5bedf1.js:7
n @ chunk-vendors.6d5bedf1.js:7
Qi.a._wrapper @ chunk-vendors.6d5bedf1.js:7
app.b1737bd9.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'status')
at m (app.b1737bd9.js:1:1829529)
m @ app.b1737bd9.js:1
Promise.then (async)
r @ chunk-vendors.6d5bedf1.js:1
s @ chunk-vendors.6d5bedf1.js:1
(anonymous) @ chunk-vendors.6d5bedf1.js:1
(anonymous) @ chunk-vendors.6d5bedf1.js:1
(anonymous) @ chunk-0d74f9e9.aa4c75f6.js:1
u @ chunk-vendors.6d5bedf1.js:255
(anonymous) @ chunk-vendors.6d5bedf1.js:255
u @ chunk-vendors.6d5bedf1.js:1
(anonymous) @ chunk-vendors.6d5bedf1.js:1
u @ chunk-vendors.6d5bedf1.js:1
o @ chunk-vendors.6d5bedf1.js:1
s @ chunk-vendors.6d5bedf1.js:1
W @ chunk-vendors.6d5bedf1.js:1
(anonymous) @ chunk-vendors.6d5bedf1.js:1
(anonymous) @ chunk-vendors.6d5bedf1.js:1
g @ chunk-vendors.6d5bedf1.js:1
(anonymous) @ chunk-vendors.6d5bedf1.js:1
(anonymous) @ chunk-vendors.6d5bedf1.js:1
x @ chunk-vendors.6d5bedf1.js:1
validate @ chunk-vendors.6d5bedf1.js:1
validateFieldsInternal @ chunk-vendors.6d5bedf1.js:255
(anonymous) @ chunk-vendors.6d5bedf1.js:255
validateFields @ chunk-vendors.6d5bedf1.js:255
(anonymous) @ chunk-0d74f9e9.aa4c75f6.js:1
d @ chunk-vendors.6d5bedf1.js:101
(anonymous) @ chunk-vendors.6d5bedf1.js:101
(anonymous) @ chunk-vendors.6d5bedf1.js:101
r @ chunk-vendors.6d5bedf1.js:1
s @ chunk-vendors.6d5bedf1.js:1
(anonymous) @ chunk-vendors.6d5bedf1.js:1
(anonymous) @ chunk-vendors.6d5bedf1.js:1
handleSubmit @ chunk-0d74f9e9.aa4c75f6.js:1
nt @ chunk-vendors.6d5bedf1.js:7
n @ chunk-vendors.6d5bedf1.js:7
nt @ chunk-vendors.6d5bedf1.js:7
Tn.e.$emit @ chunk-vendors.6d5bedf1.js:7
handleClick @ chunk-vendors.6d5bedf1.js:255
nt @ chunk-vendors.6d5bedf1.js:7
n @ chunk-vendors.6d5bedf1.js:7
Qi.a._wrapper @ chunk-vendors.6d5bedf1.js:7

### Version

newest

**Comment by Selina316** [comment]
你是什么操作系统呢 @abelit

**Comment by abelit** [comment]
> 你是什么操作系统呢 @abelit

宿主机是CentOS 7.9 和ArchLinux都遇到这样的问题。

**Comment by pycook** [comment]
你看看你api容器里的celery worker都正常开启没 @abelit

**Comment by abelit** [comment]
> 你看看你api容器里的celery worker都正常开启没 @abelit

检查了api容器里面的celery worker是正常运行的，而且没有看到异常日志。
