### ISSUE TITLE
[Bug]: env本地开发环境的VUE_APP_API_BASE_URL应该是/api不是api

### ISSUE THREAD

**Issue by MentosQuan** [veops/cmdb#583]
### What happened?

A bug happened!

### Version

newest

**Comment by LHRUN** [comment]
@MentosQuan 我看了一下目前就是 /api，麻烦贴一下具体代码位置

**Comment by MentosQuan** [comment]
> @MentosQuan我目前看了一下就是 /api，麻烦贴一下具体代码位置

不好意思啊，查了下我这边的提交记录，是我这边仓库有同事改错了
