### ISSUE TITLE
[Bug]: 更新版本后在计算属性代码中无法获取拥有计算属性的变量

### ISSUE THREAD

**Issue by EdogawaKudo** [veops/cmdb#618]
### Contact Details

137658944@qq.com

### This bug is related to UI or API?

API

### What happened?

def computed():
    tmpVar = '''{{ xxx }}'''
    ...
    return tmpVar

如果xxx为拥有计算属性的变量,则无法获取到其值,之前版本可以

### Version

2.4.11

**Comment by Selina316** [comment]
计算属性是一起计算的  没有先后依赖，不支持引用其他计算属性 @EdogawaKudo
