### ISSUE TITLE
[help wanted]: 拓扑显示疑问

### ISSUE THREAD

**Issue by manchesxia** [veops/cmdb#621]
### Contact Details

466834244@.qq.com

### What is your question?

i have a question!
设置了机房-机柜-物理机/交换机-网卡，拓扑中物理机的信息无法正常显示，其余的都可以，想咨询下可能是什么原因~？
我都设置了自动关联，字段也是默认显示

### Version

newest

**Comment by manchesxia** [comment]
![Uploading screenshot-20240926-101046.png…]()

**Comment by manchesxia** [comment]
![screenshot-20240926-101046](https://github.com/user-attachments/assets/f1a9e386-80eb-4a26-95ab-dab9a72e5cef)

**Comment by Selina316** [comment]
物理机有设置展示属性吗？拓扑视图节点名称默认是模型唯一标识的值，如果设置了展示属性，拓扑视图节点名称就是展示属性的值 @manchesxia

**Comment by manchesxia** [comment]
找到原因了，拓扑设置，中心节点实例要写精确
