### ISSUE TITLE
[help wanted]: 教程写的有点烂

### ISSUE THREAD

**Issue by k-kyle** [veops/cmdb#635]
### What is your question?

连最基本的，指示在哪里配置阿里云/腾讯有key信息，导入云上数据到CMDB里面没有啊

### Version

newest

**Comment by pycook** [comment]
<img width="482" alt="image" src="https://github.com/user-attachments/assets/03d26d19-e06a-4b21-8646-80b517c0f52e">
首先云主机自动发现是社区版的，免费的！ 

你有能力不白嫖，自己写个不行？

@k-kyle

**Comment by k-kyle** [comment]
还好我没使用，要是使用了开源项目就被骂白嫖，那就别开源了。
