### ISSUE TITLE
邮件通知配置问题

### ISSUE THREAD

**Issue by lgf0325** [veops/cmdb#655]
### What is your question?

已经通过docker方式安装了message服务
mssage的服务配置如下：
![image](https://github.com/user-attachments/assets/68270083-bc9f-4306-bdd8-ef9debcd9f09)
cmdb的配置如下：
![image](https://github.com/user-attachments/assets/e8bd3040-b672-4b67-a926-ada48a58e391)
![image](https://github.com/user-attachments/assets/25a6fa68-adb6-4c6a-a56c-5981549d4432)
防火墙已经关闭，端口正常开启。邮件测试还是没有发出来，有人遇到过吗？

### Version

newest

**Comment by Selina316** [comment]
浏览器访问：http://ip:667/web，如果能正常打开服务就是正常的，如果无法打开网页，messenger服务应该不正常 @lgf0325

**Comment by Selina316** [comment]
或则把这部分内容注释掉试试
![Uploading 微信图片_20241217162331.png…]()

**Comment by Selina316** [comment]
把这部分内容内容注释掉试试
![image](https://github.com/user-attachments/assets/2f8937d6-4110-4c17-85a0-8c52c33f8b71)

**Comment by lgf0325** [comment]
> 把这部分内容内容注释掉试试 ![image](https://private-user-images.githubusercontent.com/39409446/396417031-2f8937d6-4110-4c17-85a0-8c52c33f8b71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MjQzMDIsIm5iZiI6MTczNDQyNDAwMiwicGF0aCI6Ii8zOTQwOTQ0Ni8zOTY0MTcwMzEtMmY4OTM3ZDYtNDExMC00YzE3LTg1YTAtOGM1MmMzM2Y4YjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA4MjY0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0ODM2YzFhZjQxZGMyN2ZiZTMyYzU4MjRjZGFhYmNkNDQ3OTNjNTI1NzE2ZTM4MDgwZTM0NDhjMjYyYWNmYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0ybGsy08WJE9TsNSXOgCgcg_dyKf8kAMkwGdgHIzb2o)

十分感谢，确实是注释掉就可以正常发送了
