### ISSUE TITLE
docker部署，登录提示error   Request error, please try again later

### ISSUE THREAD

**Issue by hj00494yong** [veops/cmdb#66]
docker compose 一键部署后，login页面正常，输入用户名密码 总是弹出框提示 error   Request error, please try again later，是什么原因呢

**Comment by hj00494yong** [comment]
docker 部署 ，cmdb-api里setting.xml  mysql默认配置是127.0.0.1 .启动报错
"Can't connect to MySQL server on 'mysql' ([Errno 111] Connection refused)"  ，mysql地址该如何修改 ，需要固定mysql容器ip吗

**Comment by hj00494yong** [comment]
把api/setting.py  mysql地址改为mysql容器地址，成功进去了耶

**Comment by hj00494yong** [comment]
问下这个可以切换中文吗

**Comment by bwboy** [comment]
> 把api/setting.py mysql地址改为mysql容器地址，成功进去了耶

cool

**Comment by luckydogxf** [comment]
最新版本的话，因为源码里面mysql地址是127.0.0.1,docker-compose后这个地址肯定不对，因为容器之间访问只能通过宿主机IP，或者容器名字访问，建议更改为：
# # database
SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://{user}:{password}@cmdb-db:3306/{db}?charset=utf8'
SQLALCHEMY_BINDS = {
    "user": 'mysql+pymysql://{user}:{password}@cmdb-db:3306/{db}?charset=utf8'
}
cmdb-db就是docker-compose.yml里面DB这个容器名，如果你改了，这里也应该对应更改一下。
然后docker-compose up -d
http://<IP>:8000就可以用demo/123456登录了。

**Comment by Jiaming-LUNA** [comment]
现在已经没有setting.py了，用docker compose一键安装的打不开

**Comment by ivonGwy** [comment]
新版本不存在这个问题
